version: 2

defaults: &defaults
  working_directory: ~/project/nuxt
  docker:
    - image: banian/node-headless-chrome

jobs:
  setup:
    <<: *defaults
    steps:
      # Checkout repository
      - checkout

      # Restore cache
      - restore_cache:
          key: yarn-{{ checksum "yarn.lock" }}

      # Install dependencies
      - run:
          name: Install Dependencies
          command: NODE_ENV=dev yarn

      # Keep cache
      - save_cache:
          key: yarn-{{ checksum "yarn.lock" }}
          paths:
            - "node_modules"

      # Persist files
      - persist_to_workspace:
          root: ~/project
          paths:
            - nuxt

  lint:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Lint and Security
          command: yarn lint

  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Build Fixtures
          command: yarn generate
      - persist_to_workspace:
          root: ~/project
          paths:
            - nuxt/dist
    environment:
      - NODE_ENV: "dev"

workflows:
  version: 2
  setup-and-parallel-test:
    jobs:
      - setup

      - lint:
          requires:
            - setup

      - build:
          requires:
            - setup

      - release:
          requires:
            - build
            - lint
          filters:
            branches:
              only:
                - dev